server:
  port: 8084
spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/chat-db
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  application:
    name: CHAT-API

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8086/eureka
  instance:
    hostname: localhost